#!/bin/bash

if [ -z "$1" ]
  then
    echo "ERROR: No input given"
fi

yacc -d parser.y && lex lex.l && gcc -I/usr/include/python2.7 -lpython2.7 lex.yy.c y.tab.c -o qasm
echo "./qasm<$1" >> sqasm.log
