#!/bin/bash

if [ -z "$1" ]
  then
    echo "ERROR: No input given"
fi

echo 'yacc -d src/parser.y && flex src/lex.l && gcc -I./lib -lpython2.7 lex.yy.c y.tab.c -o qasm' >> sqasm.log
echo './qasm<$1' >> sqasm.log
